# Reading data
Read the train.csv file as a pandas dataframe.

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

In [39]:
import pandas as pd

titanic = pd.read_csv("train.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
import titanic_fns

In [6]:
# 3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
id_juozas = titanic_fns.name_to_id(titanic, 'Montvila, Rev. Juozas')
print("The ID of passenger Montvila, Rev. Juozas is", id_juozas)

The ID of passenger Montvila, Rev. Juozas is 887

In [9]:
# 4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

id_42 = titanic_fns.id_to_name(titanic, 42)
print("The passenger with ID 42 is", id_42)

The passenger with ID 42 is Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)

5. Print all information about the oldest passenger.

In [28]:
print("The oldest passenger was", int(titanic.loc[titanic.Age.idxmax(), "Age"]), "years old")

titanic.loc[titanic.Age.idxmax()]

The oldest passenger was 80 years old

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [21]:
new_data = titanic.iloc[:100]
new_data = new_data.loc[:, ['Pclass', 'Fare', 'Embarked']]
print(new_data)
new_data.to_csv('port_fares.csv', index=False)

    Pclass     Fare Embarked
0        3   7.2500        S
1        1  71.2833        C
2        3   7.9250        S
3        1  53.1000        S
4        3   8.0500        S
..     ...      ...      ...
95       3   8.0500        S
96       1  34.6542        C
97       1  63.3583        C
98       2  23.0000        S
99       2  26.0000        S

[100 rows x 3 columns]

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [7]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
# 7. We want to know if there were any survivors over the age of 60, print all of their information.
titanic.loc[(titanic.Survived == 1) & (titanic.Age > 60)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [24]:
# 8. How many people over 60 survived?
over_60_s = titanic.loc[(titanic.Survived == 1) & (titanic.Age > 60)]
print(len(over_60_s), " people over 60 years old survived")

5  people over 60 years old survived

In [25]:
# 9. What percentage of people over 60 survived?
over_60_n = titanic.loc[(titanic.Survived == 0) & (titanic.Age > 60)]
all_over_60 = len(over_60_s) + len(over_60_n)
per_60 = (len(over_60_s)/all_over_60)*100

print(round(per_60,2), "% over 60 years old survived")

22.73 % over 60 years old survived

In [29]:
titanic.Survived.value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [33]:
titanic.Pclass.value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [44]:
# Cuántas personas de cada clase sobrevivieron/fallecieron
titanic.groupby("Survived")["Pclass"].value_counts()

Survived  Pclass
0         3         372
          2          97
          1          80
1         1         136
          3         119
          2          87
Name: count, dtype: int64

In [ ]:
# Promedio de edad por clase de las personas que sobrevivieron/fallecieron
titanic.groupby(["Survived", "Pclass"])["Age"].mean()

Survived  Pclass
0         1         43.695312
          2         33.544444
          3         26.555556
1         1         35.368197
          2         25.901566
          3         20.646118
Name: Age, dtype: float64

# Women and children first?
10. Find out if women and children were more likely to survive.

In [ ]:
# Cantidad de mujeres mayores de 15 años que sobrevivieron/fallecieron (women)
women = titanic.loc[(titanic.Sex == "female") & (titanic.Age>15)]
print("Mujeres en el barco: ", len(women))
women.groupby("Survived").size()

Mujeres en el barco:  218

Survived
0     49
1    169
dtype: int64

In [35]:
# Cantidad de personas menores de 15 años que sobrevivieron/fallecieron (children)
children = titanic.loc[(titanic.Age<15)]
print("Niños en el barco: ", len(children))
children.groupby("Survived").size()

Niños en el barco:  78

Survived
0    33
1    45
dtype: int64

In [ ]:
# Cantidad de hombres mayores de 15 años que sobrevivieron/fallecieron (men)
men = titanic.loc[(titanic.Sex == "male") & (titanic.Age>15)]
print("Hombres en el barco: ", len(men))
men.groupby("Survived").size()

Hombres en el barco:  413

Survived
0    341
1     72
dtype: int64

La suma de hombres + mujeres + niños da como resultado 709 y en la base de datos original hay 891 registros, por lo que se infiere que hay pasajeros de los cuales no ese tiene registrado su género o edad.
Para determinar si las mujeres y niños tenían más probabilidad de sobrevivir, se tomará la suma de los pasajeros con los datos completos (709), ya que en base a ellos se obtuvieron las estadísticas por grupo-

In [74]:
# Porcentaje de mujeres y niños sobrevivientes
print("El porcentaje de mujeres y niños que sobrevivieron fue de", round((((169+45)/len(men+women+children))*100),2),"%")
# Cantidad de filas en la base de datos original
# len(titanic)

El porcentaje de mujeres y niños que sobrevivieron fue de 30.18 %

En conclusión, las mujeres y niños no tenían más probabilidades de sobrevivir, basados en el porcentaje de ellos que sobrevivieron y en la proporción que ellos ocupaban de los pasajeros totales.

In [ ]:
# Base solamente con los sobrevivientes
sobrevivientes = titanic.loc[titanic["Survived"] == 1]

sobrevivientes.groupby("Sex").size()

# Como todas las niñas (mujeres menores a 15 años) ya están incluidas en "female" y parte de los niños (hombres menores a 15 años) están incluidos en "male"
# si solo nos quedaramos con este dato, podríamos afirmar que las mujeres y niños tenían más probabilidad de sobrevivir.
# No obstante, aquí no se está considerando la proporción de ellos que había originalmente en el barco, por lo que sería un análisis "a medias".

Sex
female    233
male      109
dtype: int64

(Me acabo de dar cuenta que esta pregunta la contesté en español cuando todo lo habíamos hecho en inglés, a partir de la siguiente corregiré el idioma)

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

In [81]:
def perc_survived(subset: pd.Series) -> float:
    """
    Input: Subset given as a boolean Pandas series (True == survived)
    Output: Percentage of people who survived.
    """
    total_survivors = subset.sum()  # Sum of True in subset == # of survivors
    total_people = len(subset)
    per_s = (total_survivors / total_people) * 100
    return per_s

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

In [ ]:
# 12. What is the median age of the passengers?
int(titanic["Age"].median())

28

In [87]:
# titanic.head()
#  13. How many passengers embarked from each port?

titanic.groupby("Embarked").size()

Embarked
C    168
Q     77
S    644
dtype: int64

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

# Vectorizing

In [1]:
import time
import numpy as np

# Código con bucle for
start = time.time()

total = 0
for i in np.arange(10000000):
    total = i + total

print(total)
end = time.time()
print(end - start)

49999995000000
2.1638870239257812

In [2]:
start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()
print(end - start)

49999995000000
0.1309511661529541