# Reading data
Read the train.csv file as a pandas dataframe.

In [2]:
import pandas as pd

# Carga el archivo CSV en un DataFrame
tabla = pd.read_csv("dataaa/train.csv")

tabla

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

5. Print all information about the oldest passenger.

In [3]:
import titanic_fns

In [4]:
titanic_fns.id_nombre(10,tabla)

'Nasser, Mrs. Nicholas (Adele Achem)'

In [5]:
titanic_fns.nombre_id("Nasser, Mrs. Nicholas (Adele Achem)",tabla)

np.int64(10)

In [6]:
tabla[tabla.PassengerId==6].Name

5    Moran, Mr. James
Name: Name, dtype: object

In [7]:
nombre = tabla[tabla["Name"] == "Montvila, Rev. Juozas"]["PassengerId"].iloc[0]

print("The ID pf passenger Montvila, Rev. Juozas is",nombre)

The ID pf passenger Montvila, Rev. Juozas is 887

In [8]:
id_seleccion = tabla[tabla["PassengerId"] == 42]["Name"].iloc[0]

print("The passenger with ID 42 is: ",id_seleccion)

The passenger with ID 42 is:  Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)

In [9]:
Pasajero_con_mayor_edad=tabla["Age"].max()

info = tabla[tabla["Age"] == Pasajero_con_mayor_edad][["PassengerId", "Name"]].iloc[0]

print(Pasajero_con_mayor_edad,info)

80.0 PassengerId                                     631
Name           Barkworth, Mr. Algernon Henry Wilson
Name: 630, dtype: object

In [10]:
tabla.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [11]:
nueva_tabla = tabla[["Ticket", "Fare", "Embarked"]].iloc[:100]

nueva_tabla.to_csv("dataaa/port_fares.cvs")

In [12]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
import time

start =time.time()

total=0

for i in np.arange(10000000):
    total=i+total
print(total)
end=time.time()

print(end-start)

49999995000000
1.0077106952667236

In [14]:
import time

start =time.time()

print(np.sum(np.arange(10000000)))

end=time.time()

print(end-start)

49999995000000
0.04891228675842285

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [15]:
surv=tabla[(tabla["Age"]>60) & (tabla["Survived"]==1)]

surv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [16]:
len(surv)

5

In [17]:
over=tabla[(tabla["Age"]>60)]
len(over)

22

In [18]:
print("El porcentaje de personas mayores a 60 que sobrevivieron es:",len(surv)*100/len(over),"%")

El porcentaje de personas mayores a 60 que sobrevivieron es: 22.727272727272727 %

# Women and children first?
10. Find out if women and children were more likely to survive.

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

In [19]:
w_child = (tabla["Sex"] == "female") | (tabla["Age"] < 18)

surviv= tabla[w_child]["Survived"].sum()

n_m = surviv / len(tabla[w_child])

homb = (tabla["Sex"] == "male") | (tabla["Age"] >= 18)
surviv_m = tabla[homb]["Survived"].sum()
survival_r = surviv_m / len(tabla[homb])

print(f"Tasa de supervivencia de mujeres y niños: {n_m:.2%}")
print(f"Tasa de supervivencia de hombres adultos: {survival_r:.2%}")

Tasa de supervivencia de mujeres y niños: 68.82%
Tasa de supervivencia de hombres adultos: 34.23%

In [ ]:
def por(obj:pd.Series) -> float:
    return obj.mean() *100


subset1 = (tabla["Sex"] == "female") & (tabla["Age"] < 18)
subset2 = (tabla["Sex"] == "male") & (tabla["Age"] > 18)

print(f"{por(tabla.loc[subset1, 'Survived']):.2f}%")  
print(f"{por(tabla.loc[subset2, 'Survived']):.2f}%")

69.09%
18.06%

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

In [21]:
tabla["Age"].median()

np.float64(28.0)

In [22]:
tabla["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

 Hay informacion que compruebe que entre mejor clase en el barco era mas probable sobrevivir

In [23]:
survi_class = tabla.groupby("Pclass")["Survived"].mean() * 100

for pclass, rate in survi_class.items():
    print(f"Probabilidad de sobrevivir por clase {pclass}: {rate:.2f}%")

Probabilidad de sobrevivir por clase 1: 62.96%
Probabilidad de sobrevivir por clase 2: 47.28%
Probabilidad de sobrevivir por clase 3: 24.24%

Las mujeres son las que mas tienen probabilidad de sobrevivir

In [24]:
survi_gen = tabla.groupby("Sex")["Survived"].mean()*100

for sex, rate in survi_gen.items():
    print(f"Probabilidad de sobrevivir por genero  {sex}: {rate:.2f}%")

Probabilidad de sobrevivir por genero  female: 74.20%
Probabilidad de sobrevivir por genero  male: 18.89%