# Reading data
Read the train.csv file as a pandas dataframe.

In [3]:
import pandas as pd
train_data = pd.read_csv("data/train.csv")

train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

In [26]:
def getPassengerName_byId(df:pd.DataFrame,id: int) -> str:
    """Returns the name of the passenger according to the specified id

    Args:
        df (pd.DataFrame): Dataframe used
        id (int): Id of passenger

    Returns:
        str: A string conaining the name of the passenger
    """
    return df[df.PassengerId == id].Name.iloc[0]

def getPassengerId_byName(df:pd.DataFrame, name: str) -> int:
    """Returns the id of the passenger according to a given name

    Args:
        df (pd.DataFrame): DataFrame used
        name (str): Name of the passenger

    Returns:
        int: Id of the passenger
    """
    return int(df[df.Name == name]["PassengerId"].iloc[0])

In [29]:
print('The ID pf passenger Montvila, Rev. Juozas is', getPassengerId_byName(train_data,"Montvila, Rev. Juozas"))

The ID pf passenger Montvila, Rev. Juozas is 887

In [30]:
print('The passenger with ID 42 is', getPassengerName_byId(train_data,42))

The passenger with ID 42 is Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)

5. Print all information about the oldest passenger.

In [41]:
max_age = train_data.Age.max()

info_max_age = train_data[train_data.Age == max_age]

info_max_age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [44]:
port_fares = train_data.loc[:99, ["Ticket", "Fare", "Embarked"]]

port_fares.to_csv("data/port_fares.csv")

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [46]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# Women and children first?
10. Find out if women and children were more likely to survive.

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

# Vectorizacion

Algunas funciones se mandan a procesar a C, por lo que se hacen mas rapido

In [2]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import time

start = time.time()

total = 0

for i in np.arange(10000000):
    total = i + total

print(total)
end = time.time()

print(end-start)

49999995000000
0.9617922306060791

In [4]:
start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()

print(end-start)

49999995000000
0.025832414627075195