# Reading data
Read the train.csv file as a pandas dataframe.

In [6]:
import pandas as pd
import titanicfns as fn
train = pd.read_csv('data/train.csv')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

In [34]:
def id_to_name(df, id: int) -> str:
    """_summary_

    Args:
        df (pd.DataFrame): El dataframe de pandas
        id (int): El id del pasajero

    Returns:
        str: Nombre del pasajero
    """
    return df[df.PassengerId == id].Name.values[0]


def name_to_id(df, name: str) -> int:
    """_summary_

    Args:
        df (pd.DataFrame): El dataframe de pandas
        name (str): El nombre del pasajero

    Returns:
        int: El id del pasajero
    """
    return df[df.Name == name].PassengerId.values[0]

# Test the functions
name_to_id(train, 'Montvila, Rev. Juozas')
id_to_name(train, 10)

# Print message for Montvila, Rev. Juozas
name_id = fn.name_to_id(train, 'Montvila, Rev. Juozas')
print(f'The Id of passanger Montvila, Rev. Juozas is {name_id}')

# Print message for passenger with ID 42
name_name = id_to_name(train, 42)
print(f'The name of passanger with ID 42 is {name_name}')

The Id of passanger Montvila, Rev. Juozas is 887
The name of passanger with ID 42 is Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)

In [35]:
fn.name_to_id(train, 'Montvila, Rev. Juozas')
fn.id_to_name(train, 10)

'Nasser, Mrs. Nicholas (Adele Achem)'

5. Print all information about the oldest passenger.

In [ ]:
max_age = train['Age'].max()
print(f"The maximum age on the Titanic was {max_age} years")

# find all passengers with that age
oldest_passengers = train[train['Age'] == max_age]

print(f"\nThere {'was' if len(oldest_passengers) == 1 else 'were'} {len(oldest_passengers)} passenger(s) with this age:")
print("\nFull information about the oldest passenger(s):")
display(oldest_passengers)

The maximum age on the Titanic was 80.0 years

There was 1 passenger(s) with this age:

Full information about the oldest passenger(s):

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6.⁠ ⁠Create and save the new dataset in *data/port_fares.csv*.

In [ ]:
subset_df = train[['Pclass', 'Fare', 'Embarked']]

# take only the first 100 rows
subset_df_100 = subset_df.head(100)

# save to CSV in the directory
subset_df_100.to_csv('data/port_fares.csv', index= False) # index= False to not save the row numbers


display(subset_df_100.head(10))

   Pclass     Fare Embarked
0       3   7.2500        S
1       1  71.2833        C
2       3   7.9250        S
3       1  53.1000        S
4       3   8.0500        S
5       3   8.4583        Q
6       1  51.8625        S
7       3  21.0750        S
8       3  11.1333        S
9       2  30.0708        C

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [46]:
Surv = train[train.Survived == 1]

S60 = Surv[Surv.Age > 60]

A60 = train[train.Age > 60]

print(f"number of passangers over 60 who survived: {len(S60)}")

per_surv = len(S60) / len(A60)
per_surv = per_surv * 100
print(f"persentage of passangers over 60 who survived: {per_surv}%")

number of passangers over 60 who survived: 5
persentage of passangers over 60 who survived: 22.727272727272727%

# Women and children first?
10. Find out if women and children were more likely to survive.

In [ ]:

train["Is_Child"] = train["Age"] < 13

def survival_rate(group_filter):
    group = train[group_filter]
    return group["Survived"].mean() * 100  # convert  percentage

# survival rates
women_survival = survival_rate(train["Sex"] == "female")
children_survival = survival_rate(train["Is_Child"])
women_and_children_survival = survival_rate((train["Sex"] == "female") | train["Is_Child"])
overall_survival = survival_rate(train["Survived"].notna())


print(f"Overall Survival Rate: {overall_survival:.2f}%")
print(f"Women's Survival Rate: {women_survival:.2f}%")
print(f"Children's Survival Rate: {children_survival:.2f}%")
print(f"Women & Children Survival Rate: {women_and_children_survival:.2f}%")
print(f"Women and children were {'more' if women_and_children_survival > overall_survival else 'not more'} likely to survive than the average passenger")

Overall Survival Rate: 38.38%
Women's Survival Rate: 74.20%
Children's Survival Rate: 57.97%
Women & Children Survival Rate: 72.36%
Women and children were more likely to survive than the average passenger

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

In [17]:
def subset_survival_rate(subset: pd.Series) -> float:
    """_summary_

    Args:
        subset (pd.Series): boolean pandas series representing the subset of passengers

    Returns:
        float: persentage of the subset that survived
    """

    return train.loc[subset, "Survived"].mean() * 100

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

In [21]:
median_age = train["Age"].median()
embarked = train["Embarked"].value_counts()

# print
print(f"Median Age: {median_age}")
print("Number of Passengers Embarked from Each Port:")
print(embarked)

Median Age: 28.0
Number of Passengers Embarked from Each Port:
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

In [32]:
import matplotlib.pyplot as plt
import seaborn as sns

# Hypothesis 1: If you were a women you were more likley to survive than a man
survival_by_sex = train.groupby('Sex')['Survived'].mean() * 100
print("Survival rate by gender:")
print(f"{survival_by_sex}\n")

# Hypothesis 2: If you were a higher passanger clsas you were more likley to survive
survival_by_class = train.groupby('Pclass')['Survived'].mean() * 100
print("\nSurvival rate by class:")
print(survival_by_class)

Survival rate by gender:
Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64


Survival rate by class:
Pclass
1    62.962963
2    47.282609
3    24.236253
Name: Survived, dtype: float64

# Conlusion

Both of my hypotheses were correct, and I accept them as true. The data clearly shows that women had a higher likelihood of survival compared to men, and passengers in higher classes had better survival rates than those in lower classes.

# Tests

In [5]:
import numpy as np
import time

In [18]:
np.arange(18)

start = time.time()

total = 0

for i in range(10000000):
    total += i
print(f"Sum of numbers from 0 to 999999: {total}")
end = time.time()
print(f"Time elapsed: {end - start} seconds")

Sum of numbers from 0 to 999999: 49999995000000
Time elapsed: 0.5254111289978027 seconds

In [20]:
start = time.time()

print(np.sum(np.arange(10000000)))
	  
end = time.time()
print(f"Time elapsed: {end - start} seconds")

49999995000000
Time elapsed: 0.019494056701660156 seconds