# Reading data
Read the train.csv file as a pandas dataframe.

In [5]:
import pandas as pd
train_data = pd.read_csv("data/train.csv")

train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

In [ ]:
import titanic_fns as tf

In [14]:
print('The ID pf passenger Montvila, Rev. Juozas is', tf.getPassengerId_byName(train_data,"Montvila, Rev. Juozas"))

The ID pf passenger Montvila, Rev. Juozas is 887

In [15]:
print('The passenger with ID 42 is', tf.getPassengerName_byId(train_data,42))

The passenger with ID 42 is Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)

5. Print all information about the oldest passenger.

In [9]:
max_age = train_data.Age.max()

info_max_age = train_data[train_data.Age == max_age]

info_max_age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [10]:
port_fares = train_data.loc[:99, ["Ticket", "Fare", "Embarked"]]

port_fares.to_csv("data/port_fares.csv")

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [53]:
#7
over_60 = train_data[train_data.Age > 60]
over_60

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [54]:
#8 y 9
survived_over_60 = over_60[over_60.Survived == 1].shape[0]

print("Number of people over 60 that survived is: ", survived_over_60)
print("Percentage of people over 60 survived is: ", (survived_over_60/over_60.shape[0])*100)

Number of people over 60 that survived is:  5
Percentage of people over 60 survived is:  22.727272727272727

# Women and children first?
10. Find out if women and children were more likely to survive.

In [62]:
women_children = train_data.loc[(train_data.Sex == 'female') | (train_data.Age<18)]
women_children_survived = women_children[women_children.Survived == 1]

men = train_data.loc[(train_data.Sex == 'male') & (train_data.Age>=18)]
men_survived = men[men.Survived == 1]

print("Percentage of women and children survived: ", (women_children_survived.shape[0]/women_children.shape[0])*100)
print("Percentage of men that survived: ", (men_survived.shape[0]/men.shape[0])*100)

Percentage of women and children survived:  68.81720430107528
Percentage of men that survived:  17.72151898734177

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

# Vectorizacion

Algunas funciones se mandan a procesar a C, por lo que se hacen mas rapido

In [2]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import time

start = time.time()

total = 0

for i in np.arange(10000000):
    total = i + total

print(total)
end = time.time()

print(end-start)

49999995000000
0.9617922306060791

In [4]:
start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()

print(end-start)

49999995000000
0.025832414627075195