# Reading data
Read the train.csv file as a pandas dataframe.

In [2]:
import pandas as pd
titanic = pd.read_csv("data/train.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# Indexing
1. Create a function that returns the name of a passenger given their PassengerId.
2. Create a function that returns the PassengerId of a passenger given their Name.
3. Print a message with the ID of passenger **Montvila, Rev. Juozas** with the following format: 'The ID pf passenger Montvila, Rev. Juozas is ##'
4. Print a message with the name of the passenger with ID **42** with the following format: 'The passenger with ID 42 is X'

5. Print all information about the oldest passenger.

In [3]:
from titanic_fns import *

In [4]:
# Id of Montvila, Rev. Juozas

montvila_id = name_to_id(titanic, "Montvila, Rev. Juozas")
print("The Id of passenger Montvila, Rev. Juozas is " + str(montvila_id))

The Id of passenger Montvila, Rev. Juozas is 887

In [5]:
# Name of passenger 42

id42_name = id_to_name(titanic, 42)
print(f"The passenger with ID 42 is ", id42_name)

The passenger with ID 42 is  Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)

In [6]:
# Oldest passenger info
 
oldest_passenger = titanic["Age"].idxmax()
titanic.loc[oldest_passenger]

PassengerId                                     631
Survived                                          1
Pclass                                            1
Name           Barkworth, Mr. Algernon Henry Wilson
Sex                                            male
Age                                            80.0
SibSp                                             0
Parch                                             0
Ticket                                        27042
Fare                                           30.0
Cabin                                           A23
Embarked                                          S
Name: 630, dtype: object

# Subseting
We are asked to share data for analysis by a third party. Since our dataset contains personal details, we only want to share with them the following information: ticket classes, fares and port of embarkation. We are asked to deliver a sample of the first 100 rows of this dataset.

6. Create and save the new dataset in **data/port_fares.csv**.

In [7]:
if titanic.index.name is None: titanic.set_index("PassengerId", inplace = True)
titanic_alt = titanic.drop(columns = [columns for columns in titanic.columns if columns not in ["Ticket", "Fare", "Embarked"]])
first_100 = titanic_alt.iloc[:100]
first_100.to_csv("data/port_fares.csv")
first_100

                       Ticket     Fare Embarked
PassengerId
1                   A/5 21171   7.2500        S
2                    PC 17599  71.2833        C
3            STON/O2. 3101282   7.9250        S
4                      113803  53.1000        S
5                      373450   8.0500        S
...                       ...      ...      ...
96                     374910   8.0500        S
97                   PC 17754  34.6542        C
98                   PC 17759  63.3583        C
99                     231919  23.0000        S
100                    244367  26.0000        S

[100 rows x 3 columns]

# Counting
7. We want to know if there were any survivors over the age of 60, print all of their information.
8. How many people over 60 survived?
9. What percentage of people over 60 survived?

In [8]:
if titanic.index.name is not None: titanic = titanic.reset_index(drop = True)

# Passengers over 60
ages_over_60 = titanic[titanic["Age"] > 60]
print(f"Passengers over 60 yrs old ->", ages_over_60.shape[0])
print("")
# Survivors over 60
survivors_over_60 = ages_over_60[ages_over_60["Survived"] == 1]
print(f"Survivors over 60 yrs old ->", survivors_over_60.shape[0])
print("")

# Percentage of people over 60 that survived
percentage_survivors_over_60 = survivors_over_60.shape[0] / ages_over_60.shape[0] * 100
print(f"Percentage of people over 60 that survived ->", round(percentage_survivors_over_60, 2), "%")
print("")

survivors_over_60.iloc[::]

Passengers over 60 yrs old -> 22

Survivors over 60 yrs old -> 5

Percentage of people over 60 that survived -> 22.73 %

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
483,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
570,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
630,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
829,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

# Women and children first?
10. Find out if women and children were more likely to survive.

11. Write a function that returns the percentage of people that survived from a subset given as a boolean Pandas series.

In [9]:
women_children_survived = titanic[((titanic["Sex"] == "female") | (titanic["Age"] <= 18)) & (titanic["Survived"] == 1)][["Sex", "Age", "Survived"]]
men_survived = titanic[((titanic["Sex"] == "male") & (titanic["Age"] >= 18)) & (titanic["Survived"] == 1)][["Sex", "Age", "Survived"]]
people_survived = titanic[titanic["Survived"] == 1]


percentage_WnC = women_children_survived.shape[0] / people_survived.shape[0] * 100
percentage_M = men_survived.shape[0] / people_survived.shape[0] * 100

percentage_WnC_2 = women_children_survived.shape[0] / titanic.shape[0]* 100
percentage_M_2 = men_survived.shape[0] / titanic.shape[0] * 100

print(percentage_WnC, percentage_WnC_2)
print(percentage_M, percentage_M_2)

75.14619883040936 28.84399551066218
20.46783625730994 7.856341189674524

# Summarizing

12. What is the median age of the passengers?
13. How many passengers embarked from each port?

14. Generate two hypotheses about how does the survival rate differ among groups of passengers. Write your code to explore both hypotheses.

In [10]:
age_median = titanic["Age"].median()
print(f"Median age of the passengers: {age_median}")

Median age of the passengers: 28.0

In [16]:
ports = titanic["Embarked"].unique()
print(ports)
for port in range(len(ports)):
    x = titanic[titanic["Embarked"] == ports[port]].shape[0]
    print(f"Port: {ports[port]}, Passengers: {x} ")

['S' 'C' 'Q' nan]
Port: S, Passengers: 644
Port: C, Passengers: 168
Port: Q, Passengers: 77
Port: nan, Passengers: 0

# Time tests

In [ ]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import time

start = time.time()

total = 0
for i in np.arange(10**7):
    total = 1 + total
print(total)
end = time.time()
print(end, start)

10000000
1741909207.0127583 1741909205.6079743

In [ ]:
start = time.time()

print(np.sum(np.arange(10000000)))

end = time.time()

print(end-start)

-2014260032
0.03299093246459961